version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: before-install.sh
      timeout: 180
  ApplicationStart:
    - location: start-process.sh
timeout: 00