version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/base:2024.02
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo apt-get update && sudo apt-get install -y python3-pip
      - run: pip3 install requests
      - run:
          name: Build Docker Image
          command: docker build -t weather_app .
      - run:
          name: Run Container
          background: true
          command: docker run -d -p 8000:8000 --name weather_app_instance weather_app
      - run:
          name: Run Tests
          command: |
            python3 tests/test.py -v > test_results.xml
      - run:
          name: Stop Container
          command: docker rm -f weather_app_instance


#  upload_image_to_registry:
#    docker:
#      - image: docker:19.03.12
#    steps:
#      - checkout
#      - setup_remote_docker
#      - run:
#          name: Upload Image to GitLab Container Registry
#          command: |
#            docker tag weather_app $REGISTRY_URL/weather_app
#            docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#            docker push $REGISTRY_URL/weather_app
#
  checkov_scan:
    docker:
      - image: bridgecrew/checkov:latest
    steps:
      - checkout
      - run:
          name: Run Checkov with Specific Checks
          command: |
            checkov -d Terraform/

orbs:
  discord: teka23/discord@0.0.1

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_and_test
#      - upload_image_to_registry:
#          requires:
#            - build_and_test
#      - deploy_to_eks:
#          requires:
#            - build_and_test
